"use client"
import { useState } from "react"
import { useNavigate } from "@/lib/router"
import { ArrowRight, Check, Github, KeyRound, LogOut, RotateCcw, ShieldCheck } from "lucide-react"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { PasswordInput } from "@/components/ui/password-input"
import { Switch } from "@/components/ui/switch"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Heading, LinkButton, Notice, PageHeader, Panel, PanelHeader, StatusBadge } from "./components"
import { useSession, useUpdateProfile, useUpdatePassword, useLogout, useRepositories, useResetDemo, useGitHubStatus, useGitHubConnect, useGitHubDisconnect, useSettings, useUpdateSettings } from "@/lib/api/hooks"
import { isLive } from "@/lib/api/index"
import { validatePasswordStrength } from "@/lib/password"

export function Settings() {
  const devToolsEnabled = process.env.NEXT_PUBLIC_ENABLE_DEV_TOOLS === "true"
  const navigate = useNavigate(); const { data: session } = useSession(); const { data: reposData } = useRepositories(1, 100)
  const { mutateAsync: updateProfile } = useUpdateProfile(); const { mutateAsync: updatePassword } = useUpdatePassword(); const { mutateAsync: doLogout } = useLogout(); const { mutateAsync: resetDemo } = useResetDemo()
  const { data: github, isLoading: githubLoading } = useGitHubStatus(); const { mutateAsync: connect, isPending: connecting } = useGitHubConnect(); const { mutateAsync: disconnect, isPending: disconnecting } = useGitHubDisconnect(); const { data: preferences, isLoading: settingsLoading } = useSettings(); const { mutateAsync: savePreferences, isPending: savingPreferences } = useUpdateSettings()
  const [tab, setTab] = useState("profile"); const [name, setName] = useState(session?.name || ""); const [email, setEmail] = useState(session?.email || ""); const [saved, setSaved] = useState(false); const [passwordOpen, setPasswordOpen] = useState(false); const [currentPassword, setCurrentPassword] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [permissions, setPermissions] = useState(false); const [signout, setSignout] = useState(false); const [reset, setReset] = useState(false)
  const notifications = preferences ?? { completion: true, failure: true }; const tabs = devToolsEnabled ? ["profile", "security", "github", "notifications", "prototype"] : ["profile", "security", "github", "notifications"]
  return <>
    <PageHeader title="Settings" description="Your profile, account security, and workspace preferences." eyebrow="ACCOUNT" />
    <Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="mb-6 h-12 max-w-full justify-start gap-5 overflow-x-auto border-b px-0">{tabs.map((item) => <TabsTrigger key={item} value={item} className="h-9 flex-none px-0 text-xs capitalize">{item === "prototype" ? "Prototype controls" : item}</TabsTrigger>)}</TabsList>
      <TabsContent value="profile"><div className="grid gap-6 xl:grid-cols-3"><Panel className="xl:col-span-2"><PanelHeader title="Personal information" description="Manage the profile shown in your workspace." /><form onSubmit={async (e) => { e.preventDefault(); try { await updateProfile({ name, email }); setSaved(true); toast.success("Profile saved") } catch { toast.error("Failed to save profile") } }}><div className="space-y-5 px-5 pb-6"><div className="flex items-center gap-4"><div className="flex size-14 items-center justify-center rounded-full border bg-muted text-lg font-medium">{name.split(" ").map((p) => p[0]).slice(0, 2).join("")}</div><p className="text-sm font-medium">Profile avatar<br /><span className="text-xs font-normal text-muted-foreground">Generated from your initials.</span></p></div><div className="grid gap-5 sm:grid-cols-2"><div><label htmlFor="profile-name" className="mb-2 block text-xs font-medium">Full name</label><Input id="profile-name" required value={name} onChange={(e) => { setName(e.target.value); setSaved(false) }} className="h-10" /></div><div><label htmlFor="profile-email" className="mb-2 block text-xs font-medium">Email address</label><Input id="profile-email" type="email" required value={email} onChange={(e) => { setEmail(e.target.value); setSaved(false) }} className="h-10" /></div></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="size-4" /> Account profile</div></div><div className="flex items-center justify-between border-t bg-canvas px-5 py-4"><span className="text-xs text-muted-foreground">{saved ? "Changes saved" : "Changes apply to your account."}</span><Button type="submit"><Check className="size-3" />Save changes</Button></div></form></Panel><Panel><PanelHeader title="Account" /><div className="px-5 pb-5"><p className="text-xs leading-6 text-muted-foreground">Signed in to the Repo Security Auditor workspace.</p><Button variant="outline" className="mt-5 w-full" onClick={() => setSignout(true)}><LogOut className="size-4" />Sign out</Button></div></Panel></div></TabsContent>
      <TabsContent value="security"><div className="max-w-3xl space-y-5"><Panel><PanelHeader title="Password" description="Update your account password." /><div className="flex flex-wrap items-center justify-between gap-4 px-5 pb-5"><p className="text-xs text-muted-foreground">Password updates are handled by the account service.</p><Button variant="outline" onClick={() => setPasswordOpen(true)}><KeyRound className="size-4" />Change password</Button></div></Panel><Notice>Authentication and authorization are enforced by the backend service.</Notice></div></TabsContent>
      <TabsContent value="github">{isLive ? <div className="max-w-3xl space-y-5"><Panel><PanelHeader title="GitHub connection" description="Read-only repository access for security analysis." /><div className="px-5 pb-5"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-lg border bg-canvas"><Github className="size-5" /></span><div className="flex-1"><p className="text-sm font-medium">GitHub integration</p><p className="mt-1 text-xs text-muted-foreground">{reposData?.items.length || 0} registered repositories</p></div><StatusBadge status="Not available" /></div><p className="mt-4 text-xs leading-6 text-muted-foreground">GitHub OAuth is not exposed by the API yet. Scans run against repositories registered in this workspace.</p></div></Panel></div> : <div className="max-w-3xl space-y-5"><Panel><PanelHeader title="GitHub connection" description="Read-only repository access for security analysis." /><div className="px-5 pb-5"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-lg border bg-canvas"><Github className="size-5" /></span><div className="flex-1"><p className="text-sm font-medium">GitHub integration</p><p className="mt-1 text-xs text-muted-foreground">{reposData?.items.length || 0} registered repositories</p></div><StatusBadge status={github?.connected ? "Connected" : "Not connected"} /></div><div className="mt-5 flex gap-2"><Button variant="outline" onClick={() => setPermissions(true)}>Review permissions</Button><Button variant="outline" disabled={githubLoading || connecting || disconnecting} onClick={async () => { try { if (github?.connected) { await disconnect(); toast.success("GitHub connection disconnected") } else { await connect({}); toast.success("GitHub connection connected") } } catch (error) { toast.error(error instanceof Error ? error.message : "Could not update GitHub connection.") } }}>{connecting || disconnecting ? "Updating…" : github?.connected ? "Disconnect" : "Connect"}</Button></div></div></Panel>{!github?.connected && <Notice tone="warning">GitHub is disconnected. Existing scanner results remain available.</Notice>}</div>}</TabsContent>
      <TabsContent value="notifications"><Panel className="max-w-3xl"><PanelHeader title="Scan notifications" description="Manage notification preferences." />{([['completion', 'Scan completion', 'Let me know when scanner results are ready.'], ['failure', 'Scan or scanner failure', 'Notify me when coverage is incomplete or analysis fails.']] as const).map(([key, label, copy]) => <div key={key} className="flex items-center justify-between gap-5 border-t px-5 py-5"><div><p className="text-sm font-medium">{label}</p><p className="mt-1 text-xs text-muted-foreground">{copy}</p></div><Switch aria-label={label} checked={notifications[key]} disabled={settingsLoading || savingPreferences} onCheckedChange={async (checked) => { try { await savePreferences({ ...notifications, [key]: Boolean(checked) }); toast.success("Notification preference saved") } catch (error) { toast.error(error instanceof Error ? error.message : "Could not save preference.") } }} /></div>)}<div className="border-t bg-canvas px-5 py-4 text-xs text-muted-foreground">Preferences are saved to your account.</div></Panel></TabsContent>
      {devToolsEnabled && <TabsContent value="prototype"><Panel><PanelHeader title="Reset sample data" description="Restore the initial mock data used for local development." /><div className="px-5 pb-5"><Button variant="outline" onClick={() => setReset(true)}><RotateCcw className="size-3" />Reset sample data</Button></div></Panel></TabsContent>}
    </Tabs>
    <Dialog open={passwordOpen} onOpenChange={setPasswordOpen}><DialogContent><DialogHeader><DialogTitle>Change password</DialogTitle><DialogDescription>Verify your current password and choose a new one.</DialogDescription></DialogHeader><form onSubmit={async (e) => { e.preventDefault(); const pwdError = validatePasswordStrength(password); if (pwdError !== true) { toast.error(pwdError); return } if (password !== confirm) { toast.error("Passwords do not match."); return } try { await updatePassword({ current_password: currentPassword, new_password: password }); toast.success("Password updated"); setPasswordOpen(false); setCurrentPassword(""); setPassword(""); setConfirm("") } catch (error) { toast.error(error instanceof Error ? error.message : "Password update failed") } }} className="space-y-4"><PasswordInput required value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} placeholder="Current password" /><PasswordInput required value={password} onChange={(e) => setPassword(e.target.value)} placeholder="New password" /><PasswordInput required value={confirm} onChange={(e) => setConfirm(e.target.value)} placeholder="Confirm new password" /><Button type="submit" className="w-full">Update password</Button></form></DialogContent></Dialog>
    <Dialog open={permissions} onOpenChange={setPermissions}><DialogContent><DialogHeader><DialogTitle>Repository permissions</DialogTitle><DialogDescription>Read-only permissions requested by the GitHub integration.</DialogDescription></DialogHeader>{["Read repository metadata", "Read repository contents", "No write access", "No automatic pull requests"].map((item) => <p key={item} className="flex items-center gap-2 text-xs"><Check className="size-3.5 text-trust" />{item}</p>)}</DialogContent></Dialog>
    <Dialog open={signout} onOpenChange={setSignout}><DialogContent><DialogHeader><DialogTitle>Sign out of your workspace?</DialogTitle></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setSignout(false)}>Cancel</Button><Button onClick={async () => { await doLogout(); navigate("/login") }}>Sign out</Button></DialogFooter></DialogContent></Dialog>
    {devToolsEnabled && <Dialog open={reset} onOpenChange={setReset}><DialogContent><DialogHeader><DialogTitle>Reset sample data?</DialogTitle><DialogDescription>Restore the initial local development data.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setReset(false)}>Cancel</Button><Button onClick={async () => { await resetDemo(); setReset(false); navigate("/dashboard") }}>Reset sample data</Button></DialogFooter></DialogContent></Dialog>}
  </>
}

export function Documentation() {
  return <><PageHeader title="Built on evidence" description="How Repo Security Auditor turns scanner output into a clear developer workflow." eyebrow="HELP & DOCUMENTATION" /><div className="grid gap-5 lg:grid-cols-3">{[{ number: "01", title: "Connect & scan", copy: "Register a repository and confirm read-only access before running security analysis." }, { number: "02", title: "Understand & verify", copy: "Review normalized findings with severity, confidence, source rules, and captured evidence." }, { number: "03", title: "Fix & report", copy: "Apply remediation yourself, rescan, and export an evidence-backed report." }].map((item) => <Panel key={item.number}><div className="p-6"><p className="font-mono text-xs text-muted-foreground">{item.number}</p><Heading level={2} className="mt-4">{item.title}</Heading><p className="mt-3 text-sm leading-7 text-muted-foreground">{item.copy}</p></div></Panel>)}</div><div className="mt-6"><LinkButton to="/repositories/new" variant="default">Connect a repository<ArrowRight className="size-3" /></LinkButton></div></>
}
