# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-10-04T18:54:27+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, EmailStr, Field, conint, constr


class User(BaseModel):
    id: UUID
    name: str = Field(..., examples=['Alex Security'])
    email: EmailStr = Field(..., examples=['alex@example.com'])
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class LoginRequest(BaseModel):
    email: EmailStr = Field(..., examples=['user@example.com'])
    password: str = Field(..., examples=['SecurePassword123!'])


class RegisterRequest(BaseModel):
    name: str = Field(..., examples=['Alex'])
    email: EmailStr = Field(..., examples=['alex@example.com'])
    password: constr(min_length=8) = Field(..., examples=['SecurePassword123!'])


class AuthData(BaseModel):
    token: str = Field(..., examples=['sample.jwt.token'])
    user: User


class AuthResponse(BaseModel):
    status: str = Field(..., examples=['success'])
    data: AuthData


class UserResponse(BaseModel):
    status: str = Field(..., examples=['success'])
    data: User


class UpdateProfileRequest(BaseModel):
    name: str = Field(..., examples=['Alex Updated'])
    email: EmailStr = Field(..., examples=['alex.new@example.com'])


class ChangePasswordRequest(BaseModel):
    currentPassword: str
    newPassword: constr(min_length=8)


class PasswordResetRequest(BaseModel):
    email: EmailStr = Field(..., examples=['user@example.com'])


class PasswordResetConfirm(BaseModel):
    token: str = Field(..., examples=['valid-reset-token-xyz'])
    newPassword: constr(min_length=8)


class NotificationSettings(BaseModel):
    onScanCompletion: bool = Field(..., examples=[True])
    onScanFailure: bool = Field(..., examples=[True])


class NotificationSettingsResponse(BaseModel):
    status: str = Field(..., examples=['success'])
    data: NotificationSettings


class Repository(BaseModel):
    id: UUID
    url: str = Field(..., examples=['https://github.com/org/core-repo'])
    name: str = Field(..., examples=['core-repo'])
    owner: str = Field(..., examples=['org'])
    provider: str = Field(..., examples=['github'])
    defaultBranch: str = Field(..., examples=['main'])
    isValid: bool = Field(..., examples=[True])
    addedBy: UUID
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class RepositoryResponse(BaseModel):
    status: str = Field(..., examples=['success'])
    data: Repository


class ValidateRepositoryRequest(BaseModel):
    url: str = Field(..., examples=['https://github.com/org/sample'])


class ValidateRepositoryData(BaseModel):
    valid: bool = Field(..., examples=[True])
    name: str | None = Field(None, examples=['sample'])
    owner: str | None = Field(None, examples=['org'])
    defaultBranch: str | None = Field(None, examples=['main'])


class ValidateRepositoryResponse(BaseModel):
    status: str = Field(..., examples=['success'])
    data: ValidateRepositoryData


class Branch(BaseModel):
    name: str = Field(..., examples=['main'])
    isDefault: bool = Field(..., examples=[True])
    lastCommit: str | None = Field(None, examples=['7f3b4c1'])


class BranchListResponse(BaseModel):
    status: str = Field(..., examples=['success'])
    data: list[Branch]


class AddRepositoryRequest(BaseModel):
    url: str = Field(..., examples=['https://github.com/org/new-repo'])


class ScanStatus(StrEnum):
    queued = 'queued'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'


class FindingsCount(BaseModel):
    critical: int = Field(..., examples=[1])
    high: int = Field(..., examples=[3])
    medium: int = Field(..., examples=[5])
    low: int = Field(..., examples=[2])
    info: int = Field(..., examples=[0])


class Scan(BaseModel):
    id: UUID
    repositoryId: UUID
    branch: str = Field(..., examples=['main'])
    status: ScanStatus
    progress: conint(ge=0, le=100) = Field(..., examples=[100])
    findingsCount: FindingsCount
    startedAt: AwareDatetime | None = None
    completedAt: AwareDatetime | None = None
    cancelledAt: AwareDatetime | None = None
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class ScanResponse(BaseModel):
    status: str = Field(..., examples=['success'])
    data: Scan


class ScanProgressData(BaseModel):
    id: UUID
    status: ScanStatus
    progress: int = Field(..., examples=[45])


class ScanProgressResponse(BaseModel):
    status: str = Field(..., examples=['success'])
    data: ScanProgressData


class StartScanRequest(BaseModel):
    repositoryId: UUID
    branch: str = Field(..., examples=['develop'])


class Severity(StrEnum):
    critical = 'critical'
    high = 'high'
    medium = 'medium'
    low = 'low'
    info = 'info'


class ReviewStatus(StrEnum):
    open = 'open'
    acknowledged = 'acknowledged'
    false_positive = 'false_positive'
    resolved = 'resolved'


class Finding(BaseModel):
    id: UUID
    scanId: UUID
    repositoryId: UUID
    severity: Severity
    category: str = Field(..., examples=['Secret Exposure'])
    title: str = Field(..., examples=['Hardcoded AWS Access Key'])
    description: str = Field(
        ...,
        examples=['An AWS secret access key was found in plain text configuration.'],
    )
    filePath: str = Field(..., examples=['src/config/aws.ts'])
    lineStart: int | None = Field(None, examples=[14])
    lineEnd: int | None = Field(None, examples=[14])
    codeSnippet: str | None = Field(
        None, examples=["const AWS_KEY = 'AKIAIOSFODNN7EXAMPLE';"]
    )
    recommendation: str = Field(
        ...,
        examples=['Rotate the exposed key immediately and use environment variables.'],
    )
    aiExplanation: str | None = Field(
        None, examples=['The key was checked into git history 3 commits ago.']
    )
    reviewStatus: ReviewStatus
    reviewNote: str | None = None
    reviewedBy: UUID | None = None
    reviewedAt: AwareDatetime | None = None
    createdAt: AwareDatetime


class FindingResponse(BaseModel):
    status: str = Field(..., examples=['success'])
    data: Finding


class ReviewFindingRequest(BaseModel):
    reviewStatus: ReviewStatus
    reviewNote: str | None = Field(None, examples=['Verified false positive.'])


class ReportStatus(StrEnum):
    generating = 'generating'
    ready = 'ready'
    failed = 'failed'


class Report(BaseModel):
    id: UUID
    scanId: UUID
    status: ReportStatus
    format: str = Field(..., examples=['pdf'])
    fileUrl: str | None = Field(
        None, examples=['https://api.reposecurityauditor.io/api/reports/123/pdf']
    )
    fileSize: int | None = Field(None, examples=[245892])
    createdAt: AwareDatetime
    completedAt: AwareDatetime | None = None


class ReportResponse(BaseModel):
    status: str = Field(..., examples=['success'])
    data: Report


class GenerateReportRequest(BaseModel):
    scanId: UUID


class Repositories(BaseModel):
    total: int | None = Field(None, examples=[8])


class Scans(BaseModel):
    total: int | None = Field(None, examples=[42])
    queued: int | None = Field(None, examples=[1])
    running: int | None = Field(None, examples=[1])
    completed: int | None = Field(None, examples=[36])
    failed: int | None = Field(None, examples=[2])
    cancelled: int | None = Field(None, examples=[2])


class Findings(BaseModel):
    total: int | None = Field(None, examples=[120])
    open: int | None = Field(None, examples=[45])
    critical: int | None = Field(None, examples=[4])
    high: int | None = Field(None, examples=[12])
    medium: int | None = Field(None, examples=[18])
    low: int | None = Field(None, examples=[11])
    info: int | None = Field(None, examples=[0])


class DashboardMetricsData(BaseModel):
    repositories: Repositories
    scans: Scans
    findings: Findings
    recentScans: list[Scan]
    recentFindings: list[Finding]


class DashboardResponse(BaseModel):
    status: str = Field(..., examples=['success'])
    data: DashboardMetricsData


class GitHubIntegrationData(BaseModel):
    connected: bool = Field(..., examples=[True])
    username: str | None = Field(None, examples=['octocat'])
    connectedAt: AwareDatetime | None = None


class GitHubIntegrationResponse(BaseModel):
    status: str = Field(..., examples=['success'])
    data: GitHubIntegrationData


class PaginationMeta(BaseModel):
    page: int = Field(..., examples=[1])
    pageSize: int = Field(..., examples=[20])
    totalItems: int = Field(..., examples=[84])
    totalPages: int = Field(..., examples=[5])


class Data(BaseModel):
    message: str | None = Field(None, examples=['Operation completed successfully.'])


class GenericSuccessResponse(BaseModel):
    status: str = Field(..., examples=['success'])
    data: Data


class ErrorResponse(BaseModel):
    status: str = Field(..., examples=['error'])
    error: dict[str, Any]


class RepositoryListResponse(BaseModel):
    status: str = Field(..., examples=['success'])
    data: list[Repository]
    pagination: PaginationMeta


class ScanListResponse(BaseModel):
    status: str = Field(..., examples=['success'])
    data: list[Scan]
    pagination: PaginationMeta


class FindingListResponse(BaseModel):
    status: str = Field(..., examples=['success'])
    data: list[Finding]
    pagination: PaginationMeta


class ReportListResponse(BaseModel):
    status: str = Field(..., examples=['success'])
    data: list[Report]
    pagination: PaginationMeta
