"""create approved persistence schema

Revision ID: 6e5685c45f9c
Revises: 
Create Date: 2026-10-05 15:27:21.990110
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '6e5685c45f9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('DEVELOPER', 'SECURITY_ANALYST', 'ADMINISTRATOR')", name='ck_users_role'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_users_name_non_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('github_url', sa.String(length=1024), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'github_url', name='uq_repositories_owner_github_url')
    )
    op.create_index(op.f('ix_repositories_owner_id'), 'repositories', ['owner_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target_branch', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED')", name='ck_scans_status'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_repository_id'), 'scans', ['repository_id'], unique=False)
    op.create_index(op.f('ix_scans_requested_by'), 'scans', ['requested_by'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('total_findings', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('low_count', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('policy_status', sa.String(length=16), nullable=False),
    sa.Column('report_version', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("policy_status IN ('PASS', 'FAIL', 'NOT_EVALUATED')", name='ck_reports_policy_status'),
    sa.CheckConstraint("status IN ('QUEUED', 'GENERATING', 'READY', 'FAILED')", name='ck_reports_status'),
    sa.CheckConstraint('critical_count >= 0', name='ck_reports_critical_count'),
    sa.CheckConstraint('high_count >= 0', name='ck_reports_high_count'),
    sa.CheckConstraint('low_count >= 0', name='ck_reports_low_count'),
    sa.CheckConstraint('medium_count >= 0', name='ck_reports_medium_count'),
    sa.CheckConstraint('total_findings >= 0', name='ck_reports_total_findings'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    op.create_table('scanner_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('scanner_name', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("scanner_name IN ('SEMGREP', 'GITLEAKS', 'TRIVY', 'CHECKOV')", name='ck_scanner_runs_scanner_name'),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'TIMEOUT')", name='ck_scanner_runs_status'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_scanner_runs_attempt_count'),
    sa.CheckConstraint('finding_count >= 0', name='ck_scanner_runs_finding_count'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'scanner_name', name='uq_scanner_runs_scan_scanner')
    )
    op.create_index(op.f('ix_scanner_runs_scan_id'), 'scanner_runs', ['scan_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scanner_run_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('CODE', 'SECRET', 'DEPENDENCY', 'CONFIGURATION')", name='ck_findings_category'),
    sa.CheckConstraint("confidence IN ('LOW', 'MEDIUM', 'HIGH')", name='ck_findings_confidence'),
    sa.CheckConstraint("review_status IN ('OPEN', 'CONFIRMED', 'DISMISSED')", name='ck_findings_review_status'),
    sa.CheckConstraint("severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name='ck_findings_severity'),
    sa.CheckConstraint('line_end IS NULL OR (line_end > 0 AND (line_start IS NULL OR line_end >= line_start))', name='ck_findings_line_end_valid'),
    sa.CheckConstraint('line_start IS NULL OR line_start > 0', name='ck_findings_line_start_positive'),
    sa.ForeignKeyConstraint(['scanner_run_id'], ['scanner_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_category'), 'findings', ['category'], unique=False)
    op.create_index(op.f('ix_findings_review_status'), 'findings', ['review_status'], unique=False)
    op.create_index('ix_findings_scanner_run_fingerprint', 'findings', ['scanner_run_id', 'fingerprint'], unique=False)
    op.create_index(op.f('ix_findings_scanner_run_id'), 'findings', ['scanner_run_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('matched_value_redacted', sa.String(length=512), nullable=True),
    sa.Column('context_hash', sa.String(length=128), nullable=True),
    sa.Column('raw_reference', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("evidence_type IN ('CODE', 'DEPENDENCY', 'SECRET', 'CONFIGURATION')", name='ck_evidence_type'),
    sa.CheckConstraint('line_end IS NULL OR (line_end > 0 AND (line_start IS NULL OR line_end >= line_start))', name='ck_evidence_line_end_valid'),
    sa.CheckConstraint('line_start IS NULL OR line_start > 0', name='ck_evidence_line_start_positive'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_finding_id'), 'evidence', ['finding_id'], unique=False)
    op.create_table('finding_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('impact_summary', sa.Text(), nullable=True),
    sa.Column('remediation_guidance', sa.Text(), nullable=True),
    sa.Column('uncertainty_statement', sa.Text(), nullable=True),
    sa.Column('evidence_references', sa.JSON(), nullable=False),
    sa.Column('input_hash', sa.String(length=128), nullable=False),
    sa.Column('failure_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('QUEUED', 'GENERATING', 'READY', 'FAILED')", name='ck_finding_explanations_status'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_explanations_finding_id'), 'finding_explanations', ['finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finding_explanations_finding_id'), table_name='finding_explanations')
    op.drop_table('finding_explanations')
    op.drop_index(op.f('ix_evidence_finding_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_scanner_run_id'), table_name='findings')
    op.drop_index('ix_findings_scanner_run_fingerprint', table_name='findings')
    op.drop_index(op.f('ix_findings_review_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_category'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_scanner_runs_scan_id'), table_name='scanner_runs')
    op.drop_table('scanner_runs')
    op.drop_table('reports')
    op.drop_index(op.f('ix_scans_requested_by'), table_name='scans')
    op.drop_index(op.f('ix_scans_repository_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_repositories_owner_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
