name: CI

on:
  push:
    branches:
      - main
      - devops-setup
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check repository structure
        run: |
          echo "Repository checked out successfully."
          echo "CI workflow sis running."
          ls -la